package expDemo3;

import generic.G_Exp;
import transform.ExpAlgTransform;
import trees.ExpAlg;

/*Using our framework (that is generic queries and transformations are automatically generated). 
 * You just need to implement freeVars as a query and substVars 
 * as a transformation using the classes generated by the framework.
 * 
 */
public class ExpTest3 {

	static <Exp> Exp genExp(ExpAlg<Exp> alg){
		return alg.Add(alg.Add(alg.Lit(2), alg.Var("var1")),alg.Add(alg.Add(alg.Var("var2"), alg.Var("var3")), alg.Lit(5)));
	}
	
	static <Exp> Exp genSubst(ExpAlg<Exp> alg){
		return alg.Var("Var4");
	}
	
	public static void main(String[] args) {
		
		G_Exp gExp = genExp(new ExpAlgTransform(){});
		SubstVarsTransform3 substVars = new SubstVarsTransform3("var1", genSubst(new ExpAlgTransform(){}));
		
		StringArrayQueryExpAlg3 alg = new StringArrayQueryExpAlg3(new StringArrayMonoid3());
		String[] res = gExp.accept(substVars).accept(substVars).accept(substVars).accept(substVars).accept(alg);
		for (String s: res) System.out.println(s);
	}

}
