package expDemo4;

import generic.G_Exp;
import transform.ExpAlgTransform;
import trees.ExpAlg;

/*Using our framework (that is generic queries and transformations are automatically generated). 
 * You just need to implement freeVars as a query and substVars 
 * as a transformation using the classes generated by the framework.
 * 
 */
public class ExpTest {

	static <Exp> Exp genExp(ExpAlg<Exp> alg){
		return alg.Add(alg.Add(alg.Lit(2), alg.Var("var1")),alg.Add(alg.Add(alg.Var("var2"), alg.Var("var3")), alg.Lit(5)));
	}
	
	static <Exp> Exp genSubst(ExpAlg<Exp> alg){
		return alg.Var("Var4");
	}
	
	public static void main(String[] args) {
		
		G_Exp gExp = genExp(new ExpAlgTransform(){});
		SubstVarsTransform substVars = new SubstVarsTransform("var1", genSubst(new ExpAlgTransform(){}));
		
		FreeVarsQueryExpAlg alg = new FreeVarsQueryExpAlg(new FreeVarsMonoid());
		String[] res = gExp.accept(substVars).accept(substVars).accept(substVars).accept(substVars).accept(alg);
		for (String s: res) System.out.println(s);
		
		LitIncreaseTransform litIncreaseTransform = new LitIncreaseTransform();
		LitQueryExpAlg litQueryExpAlg = new LitQueryExpAlg(new LitMonoid());
		Integer intRes = gExp.accept(litIncreaseTransform).accept(litIncreaseTransform).accept(litIncreaseTransform).accept(litQueryExpAlg);
		System.out.println("Total Value: " + intRes);
		
	}

}
